### ISSUE TITLE
Feedback on readme and project issue report

### ISSUE THREAD

**Issue by chroy2** [cis3296s24/02-SpotiFynd#34]
I ran into a few problems with installing and running the app on macOS

1) python command does not work by default after installing the latest recommended version of python. The new commands are python3 and pip3. I know this is picky but it could cause confusion.

2) after creating a spotify dev app and getting the client id and secret there is no clear place to put these values at the time

3) Lastly after running the project without adding the id or secret the flag -s is working but the -a didnt open a webpage and I believe got caught in a loop or something.

Overall I like the project readme and presentation. Displaying the data on a webpage is very nice.

**Comment by AnimishTemple** [comment]
Thank you for the detailed issue!

**Comment by justinmmeans** [comment]
I will add a disclaimer before the installation and running requirements detailing this. Thank you.
