### ISSUE TITLE
FeedBack

### ISSUE THREAD

**Issue by tuk26019** [cis3296s24/02-SpotiFynd#45]
The readme is very nice and detail but to run python for version 3 I had to use the command python3 instead. Following the step I created an app on spotify and I did not see where I was suppose to put my client Id and client secret. I was able to run python3 main.py but I had trouble trying to search using the specific flags. When I did this python main.py -a "artist name" -d "0.3-0.6" and place and artist name I got NameError: name 'danceability' is not defined. Otherwise the project is detail with a few minor errors and the presentation looks nice.

**Comment by justinmmeans** [comment]
Thank you for the feedback. We have been collectively working on updating the readme as the command line syntax has changed a bit over the last couple of days with new features we are implementing. I am hoping that the changes will make sure this does not happen again.
