### ISSUE TITLE
Bug Report - Can't run project!

### ISSUE THREAD

**Issue by VictorTran259** [cis3296s24/02-SpotiFynd#47]
I followed the instructions in the readme, and I was unable to run the project on both my Mac M1 and my Windows desktop. 
![Capture](https://github.com/cis3296s24/02-SpotiFynd/assets/123014152/c50536a4-0b92-4960-91fe-d461395a8e4f)
This is a screenshot from my Windows desktop, but this was what I was seeing on my Mac M1 as well. Everything worked fine in the readme instructions up until the point where I tried to run the program. As you can see, there's an error with the command's syntax. I tried using main.py --help, but nothing in there was of any help to solve my issue either. Initially, I thought it was a problem with my Mac, but I guess it's a problem with the instructions in the readme, since it didn't run on my desktop either.

**Comment by justinmmeans** [comment]
Readme has been updated and should reflect the new commands.
