### ISSUE TITLE
Error. No such option: -s

### ISSUE THREAD

**Issue by MPags02** [cis3296s24/02-SpotiFynd#49]
<img width="844" alt="image" src="https://github.com/cis3296s24/02-SpotiFynd/assets/30301995/736b5ca3-abe3-4df5-bed7-cd9d3f298f7d">

This should be a screenshot of that I got when attempting to run this. I followed the instructions to get my ID and secret, and input everything I needed to. I attempted to use the example that was given in the instructions, but an error popped up saying no such option: -s.

**Comment by justinmmeans** [comment]
We currently have an issue where different search methods are implementing different flag IDs for the same information. This should be resolved shortly. Thank you.
